### PR TITLE
Add group 4's work (scaling in Y)

### PR DESCRIPTION
**Pull request by aydenp**

### CODE REVIEW

**Comment by andrewlinington** [comment]
image

Before submitting a PR please confirm that all files compile and can be run without any valgrind issues after running the valgrind ./main -t or valgrind ./main as shown in the ReadMe

**Review by andrewlinington — CHANGES_REQUESTED** [review]
PLease resolve the build errors and ensure they run before submitting a PR

**Comment by andrewlinington** [comment]
im going to close this PR untill the build is working fully as there is a lot of issues in need of resolving before this can be merged

**Comment by aydenp** [comment]
Reopening as we have fixed some issues and the entire class's code is a bit more fleshed out.

**Review by andrewlinington — CHANGES_REQUESTED** [review]
still a lot of issues with your tests. please run them with 

valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./main -t

or else this will never be merged in with the given tests. 

image

As a note if your tests are the only problem you are currently having then id suggest commenting them out and making a seperate PR for your tests when they have been fixed

**Comment by aydenp** [comment]
Thanks. We kept those in because they don't prevent compilation and as you said, tests aren't required until Wednesday (i.e. there are no side effects).

> or else this will never be merged in with the given tests.

Are comments like this necessary? A big portion of this project is communication, and failures like these aren't one-sided. Let's not be rude.

**Comment by andrewlinington** [comment]
Not being rude just honest those tests won't be merged in the current state they are in which is more what I was talking about not merging. They are very broken and were in the last merge too. Considering the goal of this merge was to fix up stuff since last time it would have been ideal to have working tests for this push. Again as I said if you choose to comment out your tests I will be more then willing to accept this PR as that is what I have told every group who wishes to submit a PR with just their code should do. If you make that change it can be merged in.

**Comment by aydenp** [comment]
To be clear, I wouldn't consider not freeing the single struct that our tests allocate per run as "very broken", as it has no side effects for other groups, and the decision to reopen this was made after weighing the impact of a tiny bit of leaked memory vs. other groups not being able to test with our code right away. I will comment out the tests, but again - really not necessary.

> Not being rude just honest

Many find your communication to be needlessly abrasive. This isn't productive to spend more time on, but I hope you take some time to think about that. We're all working towards the same thing.

**Review by cc0407 — APPROVED** [review]
Looks good! There were some valgrind errors but none coming from your group. We'll have to take a look at master to see why.

Compiles and runs without error and valgrind errors not caused by this group. Should be good to merge in :)

**Comment by andrewlinington** [comment]
seems issues were due to us still needing group 1's code so ive added a temporary block of code to initialize the values for us.

**Review by andrewlinington — APPROVED** [review]
Please ensure to finish your tests but looks good otherwise

**Pull request merged**
