### PR TITLE
test point helper functions, style changes

### PR DESCRIPTION
**Pull request by cc0407**
- added createTestPoints() to give each group a clean testing slate
- added freeTestPoints()
- removed instances of "group #" inside runAllTests()

### CODE REVIEW

**Review by aidkvndfj — CHANGES_REQUESTED** [review]
Looks good, please fix the conflicts in main.c though.

**Comment by cc0407** [comment]
merged it from master, hopefully that handled the merge conflicts.

**Comment by andrewlinington** [comment]
oops its all conflicts (jk just one second to fix them then this can be merged)

**Review by andrewlinington — APPROVED** [review]
should be good and should be how we approach this in for all other code

**Review by griffindavis55 — APPROVED** [review]

**Pull request merged**
