### PR TITLE
Fixed memory leaks

### PR DESCRIPTION
**Pull request by nnourr**

### CODE REVIEW

**Review by andrewlinington — CHANGES_REQUESTED** [review]
some issues are still present

**Comment by nnourr** [comment]
Fixed memory leaks and added comments

**Review by aidkvndfj — CHANGES_REQUESTED** [review]
image
Issues with compilation on the server, please fix.

**Comment by nnourr** [comment]
done

**Review by cc0407 — APPROVED** [review]
Nice! Just make sure you either delete the commented tests or implement them really soon because were gonna be going through and making everyone's code consistent today and tomorrow.

**Review by andrewlinington — APPROVED** [review]

**Pull request merged**
